[workspace]
members = [
    "myemma_logger",
    "myemma_panic_hook",
    "myemma_backtrace",
    "myemma_rocket_launch_errors",
    "myemma_rocket_options_fairing",
    "myemma_api_error",
]
resolver = "2"

[profile.release]
overflow-checks = true
